version: '3.8'

services:
  frontend:
    build: ./dcaw-frontend
    ports:
      - "5173:80"
    restart: unless-stopped

  backend:
    build: ./dcaw-backend
    ports:
      - "2009:2009"
    volumes:
      - ./dcaw-backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DATABASE_NAME=dcawallet_db
      - JWT_SECRET_KEY=supersecretjwtkey
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
